const dummyData = [
  {
    id: 1,
    name: 'LIDHULT',
    description: 'Rocking Chair',
    price: 379,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__2.webp',
  },
  {
    id: 1,
    name: 'VALLENTUNA',
    description: 'Swivel Recliner',
    price: 179,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/gistad-recliner__1.jpeg',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/gistad-recliner__2.webp',
  },
  {
    id: 1,
    name: 'FÄRLÖV',
    description: 'Rocking Chair',
    price: 349,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__2.webp',
  },
  {
    id: 1,
    name: 'EKTORP',
    description: 'Modular loveseat',
    price: 599,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/vedbo-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/vedbo-armchair__2.webp',
  },
  {
    id: 1,
    name: 'PELLO',
    description: 'Rocking Chair',
    price: 399,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/soederhamn-chaise-longue__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/soederhamn-chaise-longue__2.webp',
  },
  {
    id: 1,
    name: 'EKTORP',
    description: 'Modular loveseat',
    price: 599,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/vedbo-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/vedbo-armchair__2.webp',
  },
  {
    id: 1,
    name: 'LIDHULT',
    description: 'Rocking Chair',
    price: 379,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__2.webp',
  },
  {
    id: 1,
    name: 'BINGSTA',
    description: 'Chair',
    price: 399,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/radviken-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/radviken-armchair__2.webp',
  },
  {
    id: 1,
    name: 'JÄPPLING',
    description: 'Sectional, 1-seat',
    price: 159,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/koarp-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/koarp-armchair__2.webp',
  },
  {
    id: 1,
    name: 'MORABO',
    description: 'Modular loveseat',
    price: 159,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/remsta-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/remsta-armchair__2.webp',
  },
  {
    id: 1,
    name: 'LIDHULT',
    description: 'Rocking Chair',
    price: 379,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__1.webp',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/bingsta-high-back-armchair__2.webp',
  },
  {
    id: 1,
    name: 'VALLENTUNA',
    description: 'Swivel Recliner',
    price: 179,
    photo1: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/gistad-recliner__1.jpeg',
    photo2: 'https://sdc-ikea-1.s3-us-west-1.amazonaws.com/gistad-recliner__2.webp',
  },
];

module.exports = dummyData;
